import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import {
    Nav, Navbar, Spinner
} from 'react-bootstrap';
import logo from '../../assets/logo.png';
import { getIsUserLoggedIn, userLogout } from "../../services/api";

type Props = {
    children: React.ReactNode
}
export default function Layout(props: Props) {
    const [isUserLoggedIn, setIsUserLoggedIn] = useState(false)
    const [isLoading, setIsLoading] = useState(true)

    useEffect(() => {
        setIsLoading(true)
        getIsUserLoggedIn()
            .then(res => {
                const { isUserLoggedIn } = res
                if (!isUserLoggedIn) throw res.isUserLoggedIn
                setIsUserLoggedIn(isUserLoggedIn)
            })
            .catch(err => {
                console.log('error')
                window.location.href = '/login'
            })
            .finally(() => setIsLoading(false))
    }, [])

    if (!isUserLoggedIn) {
        return (
            <div
                style={{
                    display: 'flex',
                    width: '100%',
                    height: '100vh',
                    justifyContent: 'center',
                    alignItems: 'center',
                    backgroundColor: 'black'
                }}
            >
                <Spinner animation="border" />
            </div>
        )
    }

    return (
        <div
            style={{
                backgroundColor: 'black'
            }}
        >
            <Head>
                <title>Nutflix</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="favicon.ico" />
            </Head>
            <Header />
            {
                <main>
                    {
                        props.children
                    }
                </main>
            }
        </div>
    )
}

function Header() {
    return (
        <Navbar bg="dark" variant="dark">
            <div
                style={{
                    width: '100%',
                    paddingLeft: 20,
                    paddingRight: 20,
                    display: 'flex',
                    justifyContent: 'space-between'
                }}
            >
                <Navbar.Brand href="/">
                    <Image
                        src={logo}
                        height={30}
                        width={30}
                    />
                </Navbar.Brand>
                <Nav>
                    <Nav.Link
                        href='/admin'
                    >
                        Admin
                    </Nav.Link>
                    <Nav.Link
                        onClick={() => {
                            userLogout()
                                .then(() => {
                                    window.location.href = '/login'
                                })
                        }}
                    >
                        Logout
                    </Nav.Link>
                </Nav>
            </div>
        </Navbar>
    )
}