
type Config = {
    LINODE_CLUSTER_ID?: string,
    LINODE_OBJECT_STORAGE_IMAGE_BUCKET_NAME?: string,
    LINODE_API_BASE_URL?: string,
    LINODE_ACCESS_TOKEN?: string,
    LINODE_OBJECT_STORAGE_ACCESS_KEY?: string,
    LINODE_OBJECT_STORAGE_SECRET_KEY?: string,
    ADMIN_PASSWORD?: string,
    USER_PASSWORD?: string,
    REDIS_URL?: string,
    URL?: string,
}

const config: Config = {
    LINODE_CLUSTER_ID: process.env.LINODE_CLUSTER_ID,
    LINODE_OBJECT_STORAGE_IMAGE_BUCKET_NAME: process.env.LINODE_OBJECT_STORAGE_IMAGE_BUCKET_NAME,
    LINODE_API_BASE_URL: process.env.LINODE_API_BASE_URL,
    LINODE_ACCESS_TOKEN: process.env.LINODE_ACCESS_TOKEN,
    LINODE_OBJECT_STORAGE_ACCESS_KEY: process.env.LINODE_OBJECT_STORAGE_ACCESS_KEY,
    LINODE_OBJECT_STORAGE_SECRET_KEY: process.env.LINODE_OBJECT_STORAGE_SECRET_KEY,
    ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
    USER_PASSWORD: process.env.USER_PASSWORD,
    REDIS_URL: process.env.REDIS_URL,
    URL: process.env.NEXT_PUBLIC_URL,
}

export default config