FROM node:alpine
WORKDIR /usr/src/app
COPY ../ .

# set environment
ENV CHROME_BIN="/usr/bin/chromium-browser" \
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"

# install important package
RUN set -x \
    && apk update \
    && apk upgrade \
    && apk add --no-cache \
    udev \
    ttf-freefont \
    chromium
    
RUN npm install
EXPOSE 4002
CMD ["npm", "run", "dev"]