FROM node:alpine

ENV NODE_ENV=production

RUN apk add --no-cache libc6-compat

# set environment
ENV CHROME_BIN="/usr/bin/chromium-browser" \
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"

# install important package
RUN set -x \
    && apk update \
    && apk upgrade \
    && apk add --no-cache \
    udev \
    ttf-freefont \
    chromium
    
WORKDIR /app

COPY . .
RUN npm install
RUN npm run build

EXPOSE 4002
CMD ["npm", "run", "start"]