version: '2'

services:
  redis:
    image: redis:6.2-alpine
    expose:
      - 6379

  lapor:
    container_name: lapor
    restart: unless-stopped
    build: 
      context: .
      dockerfile: ./Dockerfile.production
    ports:
      - 4002:4002
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/app